### ISSUE TITLE
SSL error when import Semantics3Request

### ISSUE THREAD

**Issue by richardpenman** [Semantics3/semantics3-python#19]
I get the following error when import Semantics3Request:

```
Traceback (most recent call last):
  File "product_history.py", line 6, in <module>
    from semantics3 import Products
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/semantics3/__init__.py", line 4, in <module>
    from .semantics3 import Semantics3Request
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/semantics3/semantics3.py", line 3, in <module>
    from urltools import normalize
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/urltools/__init__.py", line 1, in <module>
    from .urltools import *
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/urltools/urltools.py", line 46, in <module>
    PSL = _get_public_suffix_list()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/urltools/urltools.py", line 38, in _get_public_suffix_list
    psl_raw = unicode(urlopen(PSL_URL).read(), 'utf-8').split('\n')
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 87, in urlopen
    return opener.open(url)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 443, in open_https
    h.endheaders(data)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 844, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1263, in connect
    server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 363, in wrap_socket
    _context=self)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 611, in __init__
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 840, in do_handshake
    self._sslobj.do_handshake()
IOError: [Errno socket error] [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:661)
```

Are there any other dependencies that should be installed, besides the mentioned requests-oauthlib?

**Comment by shaansheikh** [comment]
+1

I am having the same issue in python 3, but it seems to work fine in python 2. I am running "import semantics3". Here is the traceback

    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1318, in do_open
        encode_chunked=req.has_header('Transfer-encoding'))
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
        self._send_request(method, url, body, headers, encode_chunked)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
        self.endheaders(body, encode_chunked=encode_chunked)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
        self._send_output(message_body, encode_chunked=encode_chunked)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1026, in _send_output
        self.send(msg)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 964, in send
        self.connect()
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1400, in connect
        server_hostname=server_hostname)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 401, in wrap_socket
        _context=self, _session=session)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 808, in __init__
        self.do_handshake()
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 1061, in do_handshake
        self._sslobj.do_handshake()
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 683, in do_handshake
        self._sslobj.do_handshake()
    ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/semantics3/__init__.py", line 4, in <module>
        from .semantics3 import Semantics3Request
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/semantics3/semantics3.py", line 3, in <module>
        from urltools import normalize
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urltools/__init__.py", line 1, in <module>
        from .urltools import *
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urltools/urltools.py", line 46, in <module>
        PSL = _get_public_suffix_list()
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urltools/urltools.py", line 38, in _get_public_suffix_list
        psl_raw = unicode(urlopen(PSL_URL).read(), 'utf-8').split('\n')
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
        return opener.open(url, data, timeout)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 526, in open
        response = self._open(req, data)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 544, in _open
        '_open', req)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
        result = func(*args)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1361, in https_open
        context=self._context, check_hostname=self._check_hostname)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1320, in do_open
        raise URLError(err)
    urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)>
